rawFastqDir: /Users/ruben/Dropbox/Projects/RNAseqPipeline/Data/
resultsDir: /Users/ruben/Dropbox/Projects/RNAseqPipeline/Results/
BowtieIndexPath: /Users/ruben/Documents/genomedata/Mus_musculus/UCSC//mm10//Sequence//Bowtie2Index/genome
featureCountMethod: featureCounts
AnnotationPath: /Users/ruben/Documents/genomedata/Mus_musculus/UCSC//mm10//Annotation/Genes/genes.gtf
fastQCthreads: '1'
qualityFastqDir: /Users/ruben/Dropbox/Projects/RNAseqPipeline/Data/
tophat2threads: '1'
segmentMismatch: '1'
segmentLength: '18'
libType: fr-unstranded
paralleljobs: '2'
FCfeatureType: exon
FCmetaType: gene_name
FCthreads: '1'
HTSfeatureType: exon
HTSmetaType: gene_name
countTableOrigin: featureCounts
CtrlTag: Ctrl
TreatmentTag: KO

